language: node_js
node_js:
  - "8"
install: npm install
jobs:
  include:
    - stage: lint
      script: npm run test:lint
    - stage: coverage
      script: bash ./scripts/.travis-coverage.sh
    - # Node 9 test
      script: bash ./scripts/.travis-coverage.sh
      node_js:
        - "9"
    - # Node 10 test
      script: bash ./scripts/.travis-coverage.sh
      node_js:
        - "10"
    - stage: deploy
      script: bash ./scripts/.travis-deploy.sh
cache:
  directories:
    - node_modules
